name: go lang

env:
  APP_NAME: shippingservice

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  

jobs:
  checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  setup-go:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - run: go version

      - name: build the application
        run: go build -o $APP_NAME .

  trivy-fs-scan:
    runs-on: self-hosted
    needs: setup-go
    steps:
      - name: Trivy FS scan
        run: |
          trivy fs --format table -o fs.html .

  sonar-scan:
    runs-on: self-hosted
    needs: trivy-fs-scan
    steps:
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker-image-build:
    runs-on: self-hosted
    needs: sonar-scan
    steps:    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        run: |
          docker build -t srikanthhg/$APP_NAME:${{ github.sha }} .
      
  trivy-image-scan:
    runs-on: self-hosted
    needs: docker-image-build
    steps:
      - name: Trivy Image Scan
        run: |
          trivy image --format table -o trivy-image-report.html srikanthhg/$APP_NAME:${{ github.sha }}

  docker-login-push-image:
    runs-on: self-hosted
    needs: trivy-image-scan
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: |
            docker push srikanthhg/$APP_NAME:${{ github.sha }}

